/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Today */
        get: operations["get_today_v1_dashboard_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity
         * @description The ledger, optionally narrowed to one category. Drafts and chips are never narrowed.
         */
        get: operations["get_activity_v1_transactions_get"];
        put?: never;
        /**
         * Post Transaction
         * @description Add spending. It lands as a draft whatever route it came in by.
         */
        post: operations["post_transaction_v1_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Transaction
         * @description Correct a draft that was read wrong. Nothing already settled is editable.
         *
         *     No audit event: neither create nor any of the settle paths below writes one,
         *     and a lone entry for corrections would read as a complete trail that is not.
         */
        patch: operations["patch_transaction_v1_transactions__transaction_id__patch"];
        trace?: never;
    };
    "/v1/transactions/{transaction_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Confirm */
        post: operations["post_confirm_v1_transactions__transaction_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{transaction_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Discard */
        post: operations["post_discard_v1_transactions__transaction_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{transaction_id}/unconfirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Unconfirm */
        post: operations["post_unconfirm_v1_transactions__transaction_id__unconfirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/butler/thread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Default Thread
         * @description The user's conversation, created on first ask.
         */
        get: operations["get_default_thread_v1_butler_thread_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/butler/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thread */
        get: operations["get_thread_v1_butler_threads__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/butler/threads/{thread_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Message */
        post: operations["post_message_v1_butler_threads__thread_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/butler/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Default Message
         * @description Ask without naming a thread. The client almost always wants this one.
         */
        post: operations["post_default_message_v1_butler_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/butler/approvals/{approval_id}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Respond */
        post: operations["respond_v1_butler_approvals__approval_id__respond_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/butler/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Memories
         * @description Everything Kira believes about this user, in the order it is retrieved.
         */
        get: operations["list_memories_v1_butler_memories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/butler/memories/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Memory */
        delete: operations["delete_memory_v1_butler_memories__memory_id__delete"];
        options?: never;
        head?: never;
        /** Correct Memory */
        patch: operations["correct_memory_v1_butler_memories__memory_id__patch"];
        trace?: never;
    };
    "/v1/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Availability
         * @description What the client may offer. A dead affordance is worse than none.
         */
        get: operations["availability_v1_capture_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capture/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read Receipt */
        post: operations["read_receipt_v1_capture_receipt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capture/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read Voice */
        post: operations["read_voice_v1_capture_voice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/day-plan/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Places
         * @description The cap only filters the list; the room is what every band is judged on.
         *
         *     ``kind`` narrows to one sort of food and is echoed back beside the counts,
         *     because the client cannot read its own state against a list that is still
         *     in flight: the answer on screen has to say which kind it was actually
         *     filtered by, exactly as it says which ceiling.
         */
        get: operations["get_places_v1_day_plan_places_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/day-plan/interpret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interpret Filters
         * @description Read a sentence into the screen's own filters. It writes nothing.
         *
         *     The controls are the answer. Nothing here composes prose about the places
         *     themselves, because a paragraph sitting above the chips would be a second
         *     account of the same list with no way to tell which one the rows came from —
         *     where a chip that turned itself on is a reading the user can see and undo.
         *
         *     Either the whole filter set comes back or none of it does. The origin is
         *     echoed from the request untouched: it belongs to the device or to the KLCC
         *     fallback, and a model naming somewhere the user did not is the fabrication
         *     this refuses outright.
         */
        post: operations["interpret_filters_v1_day_plan_interpret_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/day-plan/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Plan Draft
         * @description Add a planned outing to today. It waits as a draft until it is confirmed.
         *
         *     Deliberately not a client POST to /v1/transactions with ``source: "plan"``:
         *     the date is the server's clock, the confidence band's percentage is the
         *     server's mapping, and the note that says the money has not moved is the
         *     server's wording. Left to the client, three things a plan draft depends on
         *     would be restatable by whoever called it.
         *
         *     Nothing here touches safe-to-spend, and that is the point rather than an
         *     omission — a draft is excluded from every engine calculation, so the figure
         *     on Today is the same after this call as before it.
         */
        post: operations["post_plan_draft_v1_day_plan_drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Goal */
        post: operations["create_goal_v1_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goal */
        get: operations["get_goal_v1_goals__goal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/goals/{goal_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goal Plan */
        get: operations["get_goal_plan_v1_goals__goal_id__plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/goals/{goal_id}/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Goal Scenarios */
        post: operations["post_goal_scenarios_v1_goals__goal_id__scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/goals/{goal_id}/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Goal Impact */
        post: operations["post_goal_impact_v1_goals__goal_id__impact_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityDayResponse */
        ActivityDayResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Total Sen */
            total_sen: number;
            /** Transactions */
            transactions: components["schemas"]["TransactionResponse"][];
        };
        /** ActivityResponse */
        ActivityResponse: {
            /** Drafts */
            drafts: components["schemas"]["TransactionResponse"][];
            /** Draft Total Sen */
            draft_total_sen: number;
            /** Days */
            days: components["schemas"]["ActivityDayResponse"][];
            /** Spent This Cycle Sen */
            spent_this_cycle_sen: number;
            /** Categories */
            categories: components["schemas"]["CategorySummaryResponse"][];
        };
        /** ApprovalDecisionRequest */
        ApprovalDecisionRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "accept" | "edit" | "reject";
            /** Args */
            args?: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_read_receipt_v1_capture_receipt_post */
        Body_read_receipt_v1_capture_receipt_post: {
            /** Image */
            image: string;
        };
        /** Body_read_voice_v1_capture_voice_post */
        Body_read_voice_v1_capture_voice_post: {
            /** Audio */
            audio: string;
        };
        /** ButlerApprovalResponse */
        ButlerApprovalResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Tool */
            tool: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: string;
            /** Evidence */
            evidence: [
                string,
                string
            ][];
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ButlerAskRequest */
        ButlerAskRequest: {
            /** Text */
            text: string;
            /** Attachment */
            attachment?: {
                [key: string]: unknown;
            } | null;
        };
        /** ButlerMessageResponse */
        ButlerMessageResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Evidence */
            evidence: [
                string,
                string
            ][];
            /** Attachment */
            attachment: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ButlerThreadResponse */
        ButlerThreadResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Messages */
            messages: components["schemas"]["ButlerMessageResponse"][];
            /** Pending Approvals */
            pending_approvals: components["schemas"]["ButlerApprovalResponse"][];
        };
        /**
         * CaptureAvailability
         * @description Whether the affordances should be offered at all.
         */
        CaptureAvailability: {
            /** Receipt */
            receipt: boolean;
            /** Voice */
            voice: boolean;
            /** Max Bytes */
            max_bytes: number;
        };
        /** CaptureFieldResponse */
        CaptureFieldResponse: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Confidence */
            confidence: number;
        };
        /**
         * CaptureResponse
         * @description What a reader made of a photo or a recording. Nothing is on the ledger.
         */
        CaptureResponse: {
            /** Kind */
            kind: string;
            /** Source */
            source: string;
            /** Merchant */
            merchant: string;
            /** Amount Sen */
            amount_sen: number;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Category */
            category: string;
            /** Confidence */
            confidence: number;
            /** Note */
            note: string;
            /** Transcript */
            transcript: string;
            /** Fields */
            fields: components["schemas"]["CaptureFieldResponse"][];
        };
        /** CategorySummaryResponse */
        CategorySummaryResponse: {
            /** Slug */
            slug: string;
            /** Label */
            label: string;
            /** Spent This Cycle Sen */
            spent_this_cycle_sen: number;
            /** Count */
            count: number;
        };
        /**
         * CorrectTransactionRequest
         * @description What the user says a draft should have read. Every field is optional.
         *
         *     Omitted means "leave it alone", which is why nothing here defaults to a
         *     value: a body carrying only ``amount_sen`` must not blank the merchant.
         *     ``confidence`` is absent on purpose — it is the reader's own figure, and a
         *     corrected amount clears it rather than letting a client restate it.
         */
        CorrectTransactionRequest: {
            /** Merchant */
            merchant?: string | null;
            /** Amount Sen */
            amount_sen?: number | null;
            /** Category */
            category?: string | null;
            /** Note */
            note?: string | null;
        };
        /** CreateTransactionRequest */
        CreateTransactionRequest: {
            /** Merchant */
            merchant: string;
            /** Amount Sen */
            amount_sen: number;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /**
             * Category
             * @default uncategorised
             */
            category: string;
            /**
             * Source
             * @default manual
             */
            source: string;
            /** Confidence */
            confidence?: number | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** DashboardTodayResponse */
        DashboardTodayResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Display Name */
            display_name: string;
            /** Currency */
            currency: string;
            /** Balance Sen */
            balance_sen: number;
            /** Reserved Sen */
            reserved_sen: number;
            /** Buffer Sen */
            buffer_sen: number;
            /** Goal Reserve Sen */
            goal_reserve_sen: number;
            /** Unclaimed Sen */
            unclaimed_sen: number;
            /** Per Day Sen */
            per_day_sen: number;
            /** Spent Today Sen */
            spent_today_sen: number;
            /** Safe Today Sen */
            safe_today_sen: number;
            /** Days To Payday */
            days_to_payday: number;
            /** Cycle Elapsed */
            cycle_elapsed: number;
            /** Commitment Count */
            commitment_count: number;
            /** Drafts Waiting */
            drafts_waiting: number;
            next_commitment: components["schemas"]["NextCommitmentResponse"] | null;
            /** Goals */
            goals: components["schemas"]["GoalSummaryResponse"][];
        };
        /**
         * DayPlanFilters
         * @description The Plan screen's controls, in one shape.
         *
         *     The same shape goes both ways: it is the state the screen is in when it
         *     asks, and the state it should be in afterwards. ``lat``/``lng`` travel with
         *     it because a ceiling means nothing without knowing where the list was
         *     measured from — but they are only ever echoed back, never rewritten. See
         *     ``DayPlanInterpretResponse``.
         */
        DayPlanFilters: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /**
             * Mode
             * @default walk
             * @enum {string}
             */
            mode: "walk" | "transit" | "ride";
            /**
             * Halal Only
             * @default false
             */
            halal_only: boolean;
            /** Cap Sen */
            cap_sen?: number | null;
            /** Kind */
            kind?: string | null;
            /**
             * Sort
             * @default balanced
             * @enum {string}
             */
            sort: "balanced" | "cheapest" | "closest";
        };
        /**
         * DayPlanInterpretRequest
         * @description One sentence, and the controls it is to be read against.
         *
         *     The current state is sent with the sentence rather than assumed, because
         *     most sentences only speak to one or two controls and the rest have to come
         *     back untouched.
         */
        DayPlanInterpretRequest: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /**
             * Mode
             * @default walk
             * @enum {string}
             */
            mode: "walk" | "transit" | "ride";
            /**
             * Halal Only
             * @default false
             */
            halal_only: boolean;
            /** Cap Sen */
            cap_sen?: number | null;
            /** Kind */
            kind?: string | null;
            /**
             * Sort
             * @default balanced
             * @enum {string}
             */
            sort: "balanced" | "cheapest" | "closest";
            /** Text */
            text: string;
        };
        /**
         * DayPlanInterpretResponse
         * @description What the sentence came to, and whether any of it may be applied.
         *
         *     ``filters`` is the whole new control state or it is null. There is no
         *     partial answer: a client that applied half of a request would be showing a
         *     list the user reads as the answer to all of it.
         *
         *     ``understood`` is the short line to show back, so a misreading is visible
         *     and can be corrected by tapping the chip it got wrong. It is built from the
         *     filters themselves, so it cannot describe a setting other than the one
         *     being applied. ``unread`` is whatever part of the sentence produced no
         *     filter — a place name, most often, since the origin is not the model's to
         *     set. ``reason`` says why nothing was applied, and is empty when something
         *     was.
         */
        DayPlanInterpretResponse: {
            /** Applied */
            applied: boolean;
            filters: components["schemas"]["DayPlanFilters"] | null;
            /** Understood */
            understood: string;
            /** Unread */
            unread: string;
            /** Reason */
            reason: string;
        };
        /**
         * DayPlanResponse
         * @description The places, and the figures they were judged against.
         *
         *     ``room_sen`` is stated rather than left to be inferred from ``share``: it
         *     is zero on a day already spent out, and a client dividing to recover it
         *     would turn that zero into a number the user never had.
         *
         *     ``nearby_count`` is how many places the radius held before any filter ran,
         *     ``matching_count`` how many were still standing after the halal filter, and
         *     ``kind_count`` how many of those were the kind of food that was asked for —
         *     all three before the ceiling. Without them, an empty ``places`` is
         *     unreadable: a client would have to guess which of four causes emptied it,
         *     and would blame the ceiling for a distance no ceiling can close, for a
         *     halal toggle no ceiling can reach, or for there being no noodles in this
         *     part of town. The counts nest, so the first of them that is nil is the
         *     cause.
         *
         *     ``kind`` is the food filter this list was actually built with, echoed back.
         *     Null means none was asked for. A client reads it rather than its own state
         *     for the same reason it reads ``cap_sen``: while a newly tapped filter is in
         *     flight, its own state describes a list that has not arrived yet. It is also
         *     the word every row's ``match_basis`` is about — a row saying ``inferred``
         *     is saying it was kept for this kind on a belief rather than on a tag, and
         *     the word that belief is about is the one here.
         *
         *     ``kind_count`` counts both sorts of match, because both are in ``places``.
         *     It is still the ``kind`` row of the price landscape and still the number of
         *     places a search for that word returns; which of them rest on a tag and which
         *     on a belief is on the rows themselves and nowhere else.
         *
         *     ``nearest_over_cap`` is the cheapest few places the ceiling turned away, and
         *     it is only ever non-empty when ``places`` is empty. It is a separate field
         *     rather than extra rows in ``places`` precisely so that no client can render
         *     it as though it had fitted: every place in it costs more than ``cap_sen``,
         *     each carries ``band: "over"`` to say so on the row itself, and a client that
         *     shows them owes the user a heading that says what they are. Every other
         *     filter still holds over it — halal is still halal and ``kind`` is still that
         *     kind — so the ceiling is the only thing relaxed, and only to say what the
         *     money would have to stretch to.
         */
        DayPlanResponse: {
            /** Room Sen */
            room_sen: number;
            /** Cap Sen */
            cap_sen: number;
            /** Kind */
            kind: string | null;
            /** Nearby Count */
            nearby_count: number;
            /** Matching Count */
            matching_count: number;
            /** Kind Count */
            kind_count: number;
            /** Places */
            places: components["schemas"]["PlaceResponse"][];
            /** Nearest Over Cap */
            nearest_over_cap: components["schemas"]["PlaceResponse"][];
        };
        /** GoalCreateRequest */
        GoalCreateRequest: {
            /**
             * Goal Type
             * @enum {string}
             */
            goal_type: "emergency_starter_fund" | "upcoming_bill_annual_expense" | "travel" | "big_purchase" | "wedding_event_deposit" | "house_down_payment" | "car_down_payment" | "wedding_fund" | "full_emergency_fund" | "education_family_goal" | "custom_goal";
            /** Name */
            name: string;
            /** Target Amount Sen */
            target_amount_sen: number;
            /**
             * Current Saved Sen
             * @default 0
             */
            current_saved_sen: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /**
             * Priority
             * @default flexible
             * @enum {string}
             */
            priority: "protected" | "important" | "flexible";
            /** Funding Account Ids */
            funding_account_ids?: string[];
        };
        /** GoalCreateResponse */
        GoalCreateResponse: {
            goal: components["schemas"]["GoalDetailResponse"];
            plan: components["schemas"]["GoalPlanResponse"];
        };
        /** GoalDetailResponse */
        GoalDetailResponse: {
            /**
             * Goal Id
             * Format: uuid
             */
            goal_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Goal Type
             * @enum {string}
             */
            goal_type: "emergency_starter_fund" | "upcoming_bill_annual_expense" | "travel" | "big_purchase" | "wedding_event_deposit" | "house_down_payment" | "car_down_payment" | "wedding_fund" | "full_emergency_fund" | "education_family_goal" | "custom_goal";
            /** Name */
            name: string;
            /** Currency */
            currency: string;
            /** Target Amount Sen */
            target_amount_sen: number;
            /** Current Saved Sen */
            current_saved_sen: number;
            /** Target Date */
            target_date: string | null;
            /**
             * Horizon
             * @enum {string}
             */
            horizon: "short" | "long";
            /**
             * Priority
             * @enum {string}
             */
            priority: "protected" | "important" | "flexible";
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "active" | "at_risk" | "needs_replan" | "paused" | "achieved" | "cancelled";
            /** Funding Account Ids */
            funding_account_ids: string[];
            /** Current Plan Version */
            current_plan_version?: number | null;
        };
        /** GoalImpactRequest */
        GoalImpactRequest: {
            /** Proposed Spend Sen */
            proposed_spend_sen: number;
        };
        /** GoalImpactResponse */
        GoalImpactResponse: {
            /**
             * Goal Id
             * Format: uuid
             */
            goal_id: string;
            /** Proposed Spend Sen */
            proposed_spend_sen: number;
            /** Safe To Spend */
            safe_to_spend: boolean;
            /** Protected Money Touched */
            protected_money_touched: boolean;
            /** Goal Reserve Shortfall Sen */
            goal_reserve_shortfall_sen: number;
            /** Projected Completion Date */
            projected_completion_date: string | null;
            /** Goal Delay Days */
            goal_delay_days: number;
            /** Flexible Spending Remaining Sen */
            flexible_spending_remaining_sen: number;
            /** Risk Flags */
            risk_flags: string[];
            /** Assumptions */
            assumptions: string[];
            /** Calculation Version */
            calculation_version: string;
            /** Evidence Refs */
            evidence_refs: string[];
        };
        /** GoalMilestoneResponse */
        GoalMilestoneResponse: {
            /** Percentage */
            percentage: number;
            /** Amount Sen */
            amount_sen: number;
            /**
             * Projected Date
             * Format: date
             */
            projected_date: string;
        };
        /** GoalPlanResponse */
        GoalPlanResponse: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /**
             * Goal Id
             * Format: uuid
             */
            goal_id: string;
            /** Version */
            version: number;
            /**
             * Approval Status
             * @enum {string}
             */
            approval_status: "draft" | "approved" | "superseded";
            /** Feasible */
            feasible: boolean;
            /** Target Amount Sen */
            target_amount_sen: number;
            /** Current Saved Sen */
            current_saved_sen: number;
            /** Remaining Amount Sen */
            remaining_amount_sen: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** Required Contribution Per Payday Sen */
            required_contribution_per_payday_sen: number;
            /** Next Required Reserve Sen */
            next_required_reserve_sen: number;
            /** Projected Completion Date */
            projected_completion_date: string | null;
            /** Milestones */
            milestones: components["schemas"]["GoalMilestoneResponse"][];
            /** Risk Flags */
            risk_flags: string[];
            /** Assumptions */
            assumptions: string[];
            /** Calculation Version */
            calculation_version: string;
            /** Evidence Refs */
            evidence_refs: string[];
        };
        /** GoalScenarioResponse */
        GoalScenarioResponse: {
            /**
             * Scenario Id
             * Format: uuid
             */
            scenario_id: string;
            /**
             * Goal Id
             * Format: uuid
             */
            goal_id: string;
            /** Label */
            label: string;
            /** Feasible */
            feasible: boolean;
            /** Contribution Per Payday Sen */
            contribution_per_payday_sen: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** Goal Delay Days */
            goal_delay_days: number;
            /** Flexible Spending Delta Sen */
            flexible_spending_delta_sen: number;
            /** Tradeoffs */
            tradeoffs: string[];
            /** Risk Flags */
            risk_flags: string[];
            /** Calculation Version */
            calculation_version: string;
            /** Evidence Refs */
            evidence_refs: string[];
        };
        /** GoalScenariosResponse */
        GoalScenariosResponse: {
            /** Scenarios */
            scenarios: components["schemas"]["GoalScenarioResponse"][];
        };
        /** GoalSummaryResponse */
        GoalSummaryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Horizon */
            horizon: string;
            /** Target Sen */
            target_sen: number;
            /** Saved Sen */
            saved_sen: number;
            /** Monthly Sen */
            monthly_sen: number;
            /** Months Left */
            months_left: number;
            /** Note */
            note: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MemoryCorrectionRequest */
        MemoryCorrectionRequest: {
            /** Fact */
            fact: string;
        };
        /** MemoryResponse */
        MemoryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Subject */
            subject: string;
            /** Fact */
            fact: string;
            /** Confidence */
            confidence: number;
            /** Source Message Id */
            source_message_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
        };
        /** NextCommitmentResponse */
        NextCommitmentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Amount Sen */
            amount_sen: number;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /** Days Until */
            days_until: number;
            /** Protected */
            protected: boolean;
        };
        /**
         * PlaceResponse
         * @description One outing, priced on the distance named by ``distance_basis``.
         *
         *     A fare is charged on the road, so ``km`` is the road distance whenever the
         *     router answered for this place. Where it did not, ``km`` falls back to the
         *     great circle, ``road_km`` is null, and ``distance_basis`` says
         *     ``straight_line`` -- which the screen has to show, because a straight-line
         *     ride fare in Kuala Lumpur can be half of the real one. The basis is
         *     per-place: one search routes some destinations and fails on others.
         *
         *     ``match_basis`` is the other thing a row must not be read without. A kind
         *     filter matches what OpenStreetMap states about a place and also what a model
         *     believes it serves beyond that, so a chicken search reaches the McDonald's
         *     that OSM only ever calls a burger shop. The two are not the same kind of
         *     truth and a client may not have to guess between them: ``tagged`` is the map
         *     stating the cuisine, ``inferred`` is a belief about the menu, and null is no
         *     kind having been asked for. A screen that drew an inferred row exactly like
         *     a tagged one would be presenting a guess as a fact -- which is the one thing
         *     a wider list must not buy.
         */
        PlaceResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Address */
            address: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Km */
            km: number;
            /** Road Km */
            road_km: number | null;
            /**
             * Distance Basis
             * @enum {string}
             */
            distance_basis: "road" | "straight_line";
            /** Travel Sen */
            travel_sen: number;
            /** Minutes */
            minutes: number;
            /** Total Sen */
            total_sen: number;
            /** Share */
            share: number | null;
            /**
             * Band
             * @enum {string}
             */
            band: "ok" | "tight" | "over";
            /** Confidence */
            confidence: string;
            /** Halal */
            halal: boolean;
            /** Note */
            note: string;
            /** Match Basis */
            match_basis: ("tagged" | "inferred") | null;
        };
        /**
         * PlanDraftRequest
         * @description A place the user tapped "Add to today" on, as the row showed it.
         *
         *     ``total_sen`` is the whole outing — meal plus travel — because that is the
         *     single figure on the row and in the sheet's total. Sending the meal alone
         *     would put a draft on screen that is not the thing the user added.
         *
         *     ``confidence`` is the place's own band, not a percentage: what "high" is
         *     worth is the server's to decide, so two clients cannot come to different
         *     answers about it. It is typed as a plain string rather than an enum because
         *     the bands come from a curated data file that is regenerated, and a word this
         *     build has not seen should cost the user their tap the least — the service
         *     reads an unfamiliar one as the least certain band.
         */
        PlanDraftRequest: {
            /** Name */
            name: string;
            /** Total Sen */
            total_sen: number;
            /** Confidence */
            confidence: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TransactionResponse */
        TransactionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Merchant */
            merchant: string;
            /** Amount Sen */
            amount_sen: number;
            /** Category */
            category: string;
            /** Category Label */
            category_label: string;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Status */
            status: string;
            /** Source */
            source: string;
            /** Confidence */
            confidence: number | null;
            /** Note */
            note: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /** Currency */
            currency: string;
            /** Buffer Sen */
            buffer_sen: number;
            /**
             * Next Payday
             * Format: date
             */
            next_payday: string;
            /**
             * Cycle Start
             * Format: date
             */
            cycle_start: string;
            /** Cycle Days */
            cycle_days: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get_today_v1_dashboard_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardTodayResponse"];
                };
            };
        };
    };
    get_activity_v1_transactions_get: {
        parameters: {
            query?: {
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_transaction_v1_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_transaction_v1_transactions__transaction_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectTransactionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_confirm_v1_transactions__transaction_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_discard_v1_transactions__transaction_id__discard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_unconfirm_v1_transactions__transaction_id__unconfirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_default_thread_v1_butler_thread_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ButlerThreadResponse"];
                };
            };
        };
    };
    get_thread_v1_butler_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ButlerThreadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_v1_butler_threads__thread_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ButlerAskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_default_message_v1_butler_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ButlerAskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    respond_v1_butler_approvals__approval_id__respond_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memories_v1_butler_memories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResponse"][];
                };
            };
        };
    };
    delete_memory_v1_butler_memories__memory_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_memory_v1_butler_memories__memory_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    availability_v1_capture_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureAvailability"];
                };
            };
        };
    };
    read_receipt_v1_capture_receipt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_read_receipt_v1_capture_receipt_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_voice_v1_capture_voice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_read_voice_v1_capture_voice_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_places_v1_day_plan_places_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                mode?: "walk" | "transit" | "ride";
                halal_only?: boolean;
                cap_sen?: number | null;
                radius_km?: number;
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interpret_filters_v1_day_plan_interpret_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayPlanInterpretRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayPlanInterpretResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_plan_draft_v1_day_plan_drafts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_goal_v1_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_goal_v1_goals__goal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_goal_plan_v1_goals__goal_id__plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_goal_scenarios_v1_goals__goal_id__scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalScenariosResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_goal_impact_v1_goals__goal_id__impact_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalImpactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalImpactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
