"""Pure finance calculations. This package imports nothing from the rest of Kira."""

from kira.engine.goal_planning import (
    CALCULATION_VERSION,
    GOAL_PRIORITIES,
    GOAL_STATUSES,
    GOAL_TYPES,
    LONG_TERM_GOAL_TYPES,
    SHORT_TERM_GOAL_TYPES,
    AccountBalance,
    ActiveGoalReserve,
    CashflowReconciliation,
    FinancialSnapshot,
    GoalContribution,
    GoalDefinition,
    GoalImpact,
    GoalMilestone,
    GoalPlan,
    GoalScenario,
    IncomePayday,
    ProtectedCommitment,
    build_goal_contribution_schedule,
    calculate_goal_feasibility,
    calculate_goal_plan_for_contribution,
    calculate_projected_completion_date,
    calculate_required_contribution,
    classify_goal_horizon,
    evaluate_goal_impact,
    generate_goal_scenarios,
    reconcile_goal_with_short_term_cashflow,
    validate_goal_definition,
    with_target_date,
)
from kira.engine.goals import months_to_goal
from kira.engine.safe_to_spend import safe_to_spend
from kira.engine.types import CommitmentInput, GoalInput, SafeToSpend, Snapshot

__all__ = [
    "CommitmentInput",
    "CALCULATION_VERSION",
    "GOAL_PRIORITIES",
    "GOAL_STATUSES",
    "GOAL_TYPES",
    "LONG_TERM_GOAL_TYPES",
    "SHORT_TERM_GOAL_TYPES",
    "AccountBalance",
    "ActiveGoalReserve",
    "CashflowReconciliation",
    "FinancialSnapshot",
    "GoalContribution",
    "GoalDefinition",
    "GoalImpact",
    "GoalInput",
    "GoalMilestone",
    "GoalPlan",
    "GoalScenario",
    "IncomePayday",
    "ProtectedCommitment",
    "SafeToSpend",
    "Snapshot",
    "months_to_goal",
    "safe_to_spend",
    "build_goal_contribution_schedule",
    "calculate_goal_feasibility",
    "calculate_goal_plan_for_contribution",
    "calculate_projected_completion_date",
    "calculate_required_contribution",
    "classify_goal_horizon",
    "evaluate_goal_impact",
    "generate_goal_scenarios",
    "reconcile_goal_with_short_term_cashflow",
    "validate_goal_definition",
    "with_target_date",
]
